version: "3.7"

services:
  validator:
    image: node:10
    command: bash -c "yarn install && yarn run dev"
    working_dir: /app
    volumes:
      - ./src:/app/src:cached
      - ./spec:/app/spec:cached
      - ./machines:/machines
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
